CREATE ROLE IF NOT EXISTS dev_sec_ops_role;


GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT CREATE USER ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT CREATE ROLE ON ACCOUNT TO ROLE dev_sec_ops_role;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE dev_sec_ops_role;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE dev_sec_ops_role WITH GRANT OPTION;

GRANT ROLE dev_sec_ops_role TO USER deployment_user;

------------------
--GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE dev_sec_ops_role;
--GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE dev_sec_ops_role WITH GRANT OPTION;




