CREATE OR ALTER TABLE COMMON.DATA_ANOMALIES (
	EVENT_ID NUMBER(38,0),
	IS_CORRECT_TIMESTAMP BOOLEAN,
	IS_CORRECT_PROCESS_NAME BOOLEAN,
    IS_OVERDUE BOOLEAN,
    DAYS_LATE NUMBER(6,0),
    SOURCE_FILENAME STRING,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	GRAPH_RUN_GROUP_ID VARCHAR(16777216)
);


create or replace TABLE COMMON.LOGGING (
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	GRAPH_RUN_GROUP_ID VARCHAR(16777216),
	TABLE_NAME VARCHAR(16777216),
	N_ROWS NUMBER(38,0),
	ERROR_MESSAGE VARCHAR(16777216)
);

create or replace TABLE COMMON.TRANSFORMATION_PIPELINE_STATUS (
	GRAPH_RUN_GROUP_ID VARCHAR(16777216),
	STARTED_AT TIMESTAMP_NTZ(9),
	FINISHED_AT TIMESTAMP_NTZ(9),
	STATUS VARCHAR(16777216)
);