CREATE OR REPLACE PROCEDURE COMMON.DATA_QUALITY("GRAPH_RUN_GROUP_ID" VARCHAR)
RETURNS INTEGER
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    LET NBRE_LIGNES_INCORRECTES INT := 0;
    INSERT INTO COMMON.DATA_ANOMALIES (EVENT_ID, IS_CORRECT_TIMESTAMP, IS_CORRECT_PROCESS_NAME, IS_OVERDUE, DAYS_LATE, SOURCE_FILENAME, GRAPH_RUN_GROUP_ID)
    WITH SOURCE AS (
        SELECT
            EVENT_ID,
            COMMON.CHECK_CORRECT_TIMESTAMP(EVENT_TIMESTAMP) AS IS_CORRECT_TIMESTAMP,
            COMMON.CHECK_CORRECT_PROCESS_NAME(PROCESS_NAME) AS IS_CORRECT_PROCESS_NAME,
            COMMON.ARRIVEE_TARDIVE(EVENT_TIMESTAMP) AS IS_OVERDUE,
            IFF(IS_OVERDUE, TIMESTAMPDIFF(DAY, EVENT_TIMESTAMP, CURRENT_TIMESTAMP()), NULL) AS DAYS_LATE,
            SOURCE_FILENAME
        FROM RAW.RAW_EVENTS
        )
    SELECT *, :GRAPH_RUN_GROUP_ID AS GRAPH_RUN_GROUP_ID
    FROM SOURCE
    WHERE IS_CORRECT_TIMESTAMP = FALSE OR IS_CORRECT_PROCESS_NAME = FALSE OR IS_OVERDUE = TRUE;
    NBRE_LIGNES_INCORRECTES:= SQLROWCOUNT;
    RETURN :NBRE_LIGNES_INCORRECTES;
END;
';


CREATE OR REPLACE PROCEDURE COMMON.LOG_RESULTS("GRAPH_RUN_GROUP_ID" VARCHAR, "TABLE_NAME" VARCHAR, "N_ROWS" NUMBER(38,0), "ERROR_MESSAGE" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
INSERT INTO COMMON.LOGGING (GRAPH_RUN_GROUP_ID, TABLE_NAME, N_ROWS, ERROR_MESSAGE)
VALUES (:GRAPH_RUN_GROUP_ID, :TABLE_NAME, :N_ROWS, :ERROR_MESSAGE);
';


CREATE OR REPLACE PROCEDURE COMMON.ENRICH_DATA("TABLE_NAME" VARCHAR, "PROCESS_NAME" VARCHAR, "GRAPH_RUN_GROUP_ID" VARCHAR)
RETURNS INTEGER
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    full_table_name STRING := CONCAT(''staging.'', :table_name);
    insert_exception EXCEPTION (-20001, ''EXCEPTION IN DATA LOADING INTO STAGING TABLES'');
BEGIN
    LET n_rows INT := 0;

    INSERT INTO IDENTIFIER(:full_table_name) (event_timestamp, process_id, log_trigger, message, source_filename)
    WITH
        source AS
            (SELECT
                re.event_timestamp,
                re.process_name,
                re.process_id,
                common.extract_log_trigger(re.message) AS log_trigger,
                common.extract_log_message(re.message) AS message,
                re.source_filename AS source_filename
            FROM raw.raw_events re
            JOIN raw.data_to_process dtp
            ON re.event_id = dtp.event_id
            LEFT JOIN common.data_anomalies da
            ON re.event_id = da.event_id
            WHERE re.process_name = :process_name
            AND da.event_id is null)
    SELECT
        event_timestamp,
        process_id,
        log_trigger,
        message,
        source_filename
    FROM source;
    n_rows := SQLROWCOUNT;

    CALL common.log_results(:GRAPH_RUN_GROUP_ID, :TABLE_NAME, :N_ROWS, NULL);
    EXCEPTION
        WHEN OTHER THEN
            CALL COMMON.LOG_RESULTS(:GRAPH_RUN_GROUP_ID, :TABLE_NAME, NULL, :SQLERRM);
        RAISE;

    return :n_rows;

END;
';


CREATE OR REPLACE PROCEDURE COMMON.FINALIZE_TRANSFORMATION("GRAPH_RUN_GROUP_ID" VARCHAR, "STARTED_AT" TIMESTAMP_NTZ(9))
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    PIPELINE_EXCEPTION EXCEPTION (-20002, ''EXCEPTION IN THE TRANSFORMATION PIPELINE'');
BEGIN
    LET N_ERRORS INT :=0;

    SELECT COUNT(*) INTO N_ERRORS
    FROM COMMON.LOGGING
    WHERE GRAPH_RUN_GROUP_ID = :GRAPH_RUN_GROUP_ID
    AND ERROR_MESSAGE IS NOT NULL;

    INSERT INTO COMMON.TRANSFORMATION_PIPELINE_STATUS (GRAPH_RUN_GROUP_ID, STARTED_AT, FINISHED_AT, STATUS)
    SELECT
        :GRAPH_RUN_GROUP_ID AS GRAPH_RUN_GROUP_ID,
        :STARTED_AT AS STARTED_AT,
        CURRENT_TIMESTAMP() AS FINISHED_AT,
        IFF(:N_ERRORS > 0, ''FAILED'', ''SUCCEEDED'') AS STATUS;

    IF (:N_ERRORS = 0) THEN
        TRUNCATE TABLE RAW.DATA_TO_PROCESS;
    ELSE
        RAISE PIPELINE_EXCEPTION;
    END IF;
END;
';


CREATE OR REPLACE PROCEDURE COMMON.IDENTIFY_NEW_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
    INSERT INTO raw.data_to_process (event_id, event_timestamp, process_name, process_id, message)
    (SELECT event_id, event_timestamp, process_name, process_id, message FROM COMMON.RAW_EVENTS_STREAM);
';


